version: "3.9"
services:
  postgres:
    image: "bitnami/postgresql:15"
    restart: "unless-stopped"
    ports:
      - "5432:5432"
    environment:
      POSTGRESQL_DATABASE: "${POSTGRESQL_DATABASE}"
      POSTGRESQL_USERNAME: "${POSTGRESQL_USERNAME}"
      POSTGRESQL_PASSWORD: "${POSTGRESQL_PASSWORD}"

  wemb-core:
    build: "."
    restart: "unless-stopped"
    depends_on:
      - "postgres"
    environment:
      WEMB_LOGLEVEL: "${WEMB_LOGLEVEL}"
      DISCORD_API_TOKEN: "${DISCORD_API_TOKEN}"
      PRAW_CLIENT_ID: "${PRAW_CLIENT_ID}"
      PRAW_CLIENT_SECRET: "${PRAW_CLIENT_SECRET}"
      PRAW_USER_AGENT: "${PRAW_USER_AGENT}"
      DB_CONNECTION_STRING: "postgresql+asyncpg://${POSTGRESQL_USERNAME}:${POSTGRESQL_PASSWORD}@postgres:5432/${POSTGRESQL_DATABASE}"
      WEMB_MENTION_STRING: "${WEMB_MENTION_STRING}"
      WEMB_WEBHOOK_URL: "${WEMB_WEBHOOK_URL}"
