version: "3.9"
services:
  wemb-core:
    build: "."
    restart: "unless-stopped"
    environment:
      - PRAW_CLIENT_ID=${PRAW_CLIENT_ID}
      - PRAW_CLIENT_SECRET=${PRAW_CLIENT_SECRET}
      - PRAW_USER_AGENT=${PRAW_USER_AGENT}
      - WEMB_DISCORD_API_TOKEN=${WEMB_DISCORD_API_TOKEN}
      - WEMB_MENTION_STRING=${WEMB_MENTION_STRING}
      - WEMB_WEBHOOK_URL=${WEMB_WEBHOOK_URL}
