name: "Build and Publish (Feature Branches)"

on:
  push:
    branches:
      - "feat/**"
      - "fix/**"
      - "test/**"

jobs:
  build-and-publish:
    uses: "./.github/workflows/build-and-publish.yaml"
    with:
      push: true
      release-type: "branch"
