name: "Tag Repository"

on:
  workflow_call:
    inputs:
      type:
        type: string
        required: true
        description: "The type of tag to apply. Valid values are 'prerelease' and 'release'."

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: "Check out repository"
        uses: actions/checkout@v3

      - name: "Validate input"
        run: |
          if [[ ! "${{ inputs.type }}" =~ ^(prerelease|release)$ ]]; then
            echo "'${{ inputs.type }}' is not a valid input for .type!" >&2
            exit 1
          fi

      - name: "Set up Python 3"
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          cache: "pip"

      - name: "Install semversioner"
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade semversioner

      - name: "Tag repo and push"
        run: |
          TAGNAME="$(semversioner current-version)"
          
          if [[ "${{ inputs.type }}" == 'prerelease' ]]; then
            TAGNAME="${TAGNAME}-prerelease"
          fi
          
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          git tag -a "${TAGNAME}"
          git push origin "${TAGNAME}"
